apiVersion: v1
kind: Pod
metadata:
  name: simple-web
  namespace: web-app-dev
spec:
  containers:
    - name: web
      image: ksxack/lesson1:v0.2

      imagePullPolicy: Always
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP